### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by VadokDev** [AxlKings/AOMUSE#1]
Great Script!, but I had a hard time learning to use it just analyzing the code, please update README in order to allow other people to use it

**Comment by AxlKings** [comment]
I just finished the README, take a look and tell me if its something wrong with it and hank you for compliment!
Greetings.

**Comment by AxlKings** [comment]
I just finished the README, take a look and tell me if its something wrong with it and thank you for compliment!
Greetings.

> Great Script!, but I had a hard time learning to use it just analyzing the code, please update README in order to allow other people to use it
